# estilos.py

# 🎨 Colores
COLOR_FONDO = "#333333"
COLOR_TEXTO = "#CCCCCC"
COLOR_ENTRADA_BG = "#555555"
COLOR_BOTON_ENTRADA = "#FF0000"
COLOR_BOTON_ENTRADA_HOVER = "#cc0000"
COLOR_BOTON_SALIDA = "#FFD700"
COLOR_BOTON_SALIDA_HOVER = "#e6c200"
COLOR_SCROLL = "#1e1e2f"
COLOR_SCROLL_HOVER = "#14141f"
COLOR_TEXTO_ENTRY = "#FFFFFF"
COLOR_CURSOR = "#FFFFFF"
COLOR_HISTORIAL_BG = "#cc0000"
COLOR_HISTORIAL_AREA = "#333333"
COLOR_HISTORIAL_TEXT = "#CCCCCC"

# 🖋️ Fuentes
FUENTE_LABEL = ("Segoe UI", 12, "bold")
FUENTE_ENTRADA = ("Segoe UI", 11)
FUENTE_BOTON = ("Segoe UI", 11, "bold")
FUENTE_LISTA = ("Segoe UI", 12, "bold")
FUENTE_HISTORIAL = ("Segoe UI", 11, "bold")
